site_name: Carteira Digital de Trânsito
theme:
  name: material
  language: pt-BR
  logo: assets/icon.png

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.extra 

nav:
  - Sobre o projeto: index.md
  - Atas:
    - Ata 01: atas/ata 1.md
    - Ata 02: atas/ata2.md
    - Ata 03: atas/ata 3.md
    - Ata 04: atas/ata4.md
    - Ata 05: atas/ata5.md
    - Ata 06: atas/ata6.md
  - Apresentações:
    - Apresentação 01: apresentação/apresentação 1
    - Apresentação 02: apresentação/apresentacao 2
    - Apresentação 03: apresentação/apresentacao 3
  - Planejamento:
    - Ferramentas: planejamento/ferramenta.md
    - Cronograma: planejamento/cronograma.md
    - Políticas: planejamento/políticas.md
    - Aplicativo Selecionado: planejamento/aplicativo
    - Heatmap: planejamento/Heatmap
    - Metodologia: planejamento/metodologia
  - Pré-rastreabilidade:
    - Rich picture: pré-rastreabilidade/rich picture
  - Rastreabilidade:
    - Matriz Geral: pos-rastreabilidade/matriz-geral.md
    - Pós-Rastreabilidade: pos-rastreabilidade/pos-rastreabilidade.md
  - Elicitação:
    - Definição Perfil de Usuário:
      - Questionário: elicitação/PerfildeUsuario/Questionario.md
      - Análise de documento: elicitação/PerfildeUsuario/AnaliseDocumento.md
      - Perfil de Usuário: elicitação/PerfildeUsuario/PerfilUsuario.md
    - Personas: elicitação/personas
    - Elicitação de Requisito: 
      - Storyboard: elicitação/storyboard
      - Glossário: elicitação/glossario
      - Entrevista: elicitação/entrevista.md
      - Introspecção: elicitação/Introspeccao.md
      - Requisitos Elicitados: elicitação/requisitos_elicitados
    - Priorização: 
      - First Things First: elicitação/priorização/first_things_first
      - Three Level Scale: elicitação/priorização/three_level_scale
      - $100: elicitação/priorização/100
  - Modelagem:
    - Cenários: modelagem/cenarios.md  
    - Casos de Uso: modelagem/casosDeUso.md
    - Léxicos: modelagem/léxicos.md
    - Elicitação Suplementar: modelagem/especificacao-suplementar
    - Ágil:
      - NFR Framework: modelagem/agil/framework.md
      - Product Backlog: modelagem/agil/backlog.md
      - Histórias de Usuário: modelagem/agil/historiasUsuario.md
  - Verificação:
    - Grupo 2:
      - planejamento da verificação: verificacao/grupo2/planejamendoDaVerificacao.md 
    - Grupo 3:
      - Planejamento da Verificação: verificacao/grupo3/planejamendoDaVerificacao.md 
      - Planejamento:
        - Padronização do projeto: verificacao/grupo3/planejamento/padronizacaoDoProj.md
        - Rich Picture: verificacao/grupo3/planejamento/richPicure.md
        - Aplicativo selecionado: verificacao/grupo3/planejamento/AplicativoSelecionado.md 
        - Cronogramas: verificacao/grupo3/planejamento/cronograma.md
        - Ferramentas de Uso: verificacao/grupo3/planejamento/ferramentasDeUso.md
        - Heatmap: verificacao/grupo3/planejamento/heatmap.md
        - Termos de Uso: verificacao/grupo3/planejamento/TermosDeUso.md 
      - Elicitação:
        - Personas: verificacao/grupo3/elicitacao/personas.md
        - Técnicas:
          - Brainstorming: verificacao/grupo3/elicitacao/tecnicasDeElicitacao/brainstorming.md
          - Introspecção: verificacao/grupo3/elicitacao/tecnicasDeElicitacao/introspeccao.md
          - Observação: verificacao/grupo3/elicitacao/tecnicasDeElicitacao/observacao.md
          - Questionário: verificacao/grupo3/elicitacao/tecnicasDeElicitacao/questionario.md
        - Priorização de requisitos:
          - $100: verificacao/grupo3/elicitacao/priorizacao/$100.md
          - Introdução: verificacao/grupo3/elicitacao/priorizacao/Introducao_Priorizacao.md
          - Moscow: verificacao/grupo3/elicitacao/priorizacao/moscow.md
          - Three Level Scale: verificacao/grupo3/elicitacao/priorizacao/ThreeLevelScale.md
      - Modelagem:
        - Cenários: verificacao/grupo3/modelagem/cenarios.md
        - Léxicos:  verificacao/grupo3/modelagem/lexicos.md
        - Casos de Uso:  verificacao/grupo3/modelagem/casosDeUso.md
        - Especificação Suplementar: verificacao/grupo3/modelagem/especificacaoSuplementar.md
      - Modelagem Àgil:
        - Backlog do produto: verificacao/grupo3/backlog.md
        - Histórias de Usuário: verificacao/grupo3/verificacao-historias-de-usuario.md
        - NFR Framework: verificacao/grupo3/modelagem/agil/nfr.md

