site_name: Carteira Digital de Trânsito
theme:
  name: material
  language: pt-BR
  logo: assets/icon.png

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.expand

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Sobre o projeto: index.md
  - Atas:
    - Ata 01: atas/ata 1
    - Ata 02: atas/ata2
  - Apresentações:
    - Apresentação 01: apresentação/apresentação 1
  - Planejamento: 
    - Ferramentas: planejamento/ferramenta
    - Cronograma: planejamento/cronograma
    - Aplicativos: planejamento/aplicativo
    - Heatmap: planejamento/Heatmap
    - Metodologia: planejamento/metodologia
  - Pré-rastreabilidade:
    - Rich picture: pré-rastreabilidade/rich picture
  - Elicitação:
    - Storyboard: elicitação/storyboard
    - Perfil de Usuário: elicitação/perfil_de_usuário
    - Personas: elicitação/personas
    - Questionário: elicitação/questionario
    - Glossário: elicitação/glossario
    - Priorização: 
      - First Things First: elicitação/priorização/first_things_first
      - Three Level Scale: elicitação/priorização/three_level_scale
      - $100: elicitação/priorização/100
    - Requisitos Elicitados: elicitação/requisitos_elicitados
