site_name: Carteira Digital de Trânsito
theme:
  name: material
  language: pt-BR
  logo: assets/icon.png

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.extra 
nav:
  - Sobre o projeto: index.md
  - Atas:
    - Ata 01: atas/ata 1.md
    - Ata 02: atas/ata2.md
    - Ata 03: atas/ata 3.md
    - Ata 04: atas/ata4.md
    - Ata 05: atas/ata5.md
  - Apresentações:
    - Apresentação 01: apresentação/apresentação 1
    - Apresentação 02: apresentação/apresentacao 2
    - Apresentação 03: apresentação/apresentacao 3
  - Planejamento: 
    - Ferramentas: planejamento/ferramenta
    - Cronograma: planejamento/cronograma
    - Aplicativos: planejamento/aplicativo
    - Heatmap: planejamento/Heatmap
    - Metodologia: planejamento/metodologia
  - Pré-rastreabilidade:
    - Rich picture: pré-rastreabilidade/rich picture
  - Elicitação:
    - Definição Perfil de Usuário:
      - Questionário: elicitação/PerfildeUsuario/Questionario.md
      - Análise de documento: elicitação/PerfildeUsuario/AnaliseDocumento.md
      - Perfil de Usuário: elicitação/PerfildeUsuario/PerfilUsuario.md
    - Personas: elicitação/personas
    - Elicitação de Requisito: 
      - Storyboard: elicitação/storyboard
      - Glossário: elicitação/glossario
      - Entrevista: elicitação/entrevista.md
      - Introspecção: elicitação/Introspeccao.md
      - Requisitos Elicitados: elicitação/requisitos_elicitados
    - Priorização: 
      - First Things First: elicitação/priorização/first_things_first
      - Three Level Scale: elicitação/priorização/three_level_scale
      - $100: elicitação/priorização/100
  - Modelagem:
    - Cenários: modelagem/cenarios.md  
    - Casos de Uso: modelagem/casosDeUso.md
    - Léxicos: modelagem/léxicos.md
    - Elicitação Suplementar: modelagem/especificacao-suplementar
    - Ágil:
      - NFR Framework: modelagem/agil/framework.md
      - Product Backlog: modelagem/agil/backlog.md
      - Histórias de Usuário: modelagem/agil/historiasUsuario.md
  - Verificação:
    - Planejamento da Verificação: verificacao/planejamendoDaVerificacao.md 
    - Planejamento:
      - Cronograma: verificacao/planejamento/cronograma.md
      - Ferramentas de uso: verificacao/ferramentasDeUso.md
      - Padronização do projeto: verificacao/padronizacaoDoProj.md
      - Rich Picture: verificacao/planejamento/richPicture.md
    - Elicitação:
      - Brainstorming: verificacao/tecnicasDeElicitacao/brainstorming.md
      - Introspecção: verificacao/tecnicasDeElicitacao/introspeccao.md
      - Observação: verificacao/tecnicasDeElicitacao/observacao.md
      - Questionário: verificacao/tecnicasDeElicitacao/questionario.md
    - Priorização:
      - Introdução: verificacao/introducao_Priorizacao.md
      - $100: verificacao/$100.md
      - Three Level Scale: verificacao/priorizacao/threeLevelScale.md
    - Modelagem:
      - Cenário: verificacao/priorizacao/cenario.md
    
      


 
