site_name: AgroMart
copyright: "🌱 Projeto AgroMart 2025.2"
theme:
  name: material
  language: pt-BR
  logo: assets/logo.png

  palette:
    # Modo claro
    - scheme: default
      primary: light-green   # <-- cor da barra
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro

    # Modo escuro
    - scheme: slate
      primary: green         # <-- cor da barra no modo escuro
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.extra 

nav:
  - Conheça o AgroMart: index.md
  - AgroMart Mobile: 
    - Conheça o AgroMart Mobile: AgroMart_Mobile/AgroMartMobile.md
    - Arquitetura Mobile: AgroMart_Mobile/arquitetura.md
    - Guia de instalação: AgroMart_Mobile/guiaUsuario.md
    - Planejamento: AgroMart_Mobile/planejamento.md
    - Padrões de Desenvolvimento: AgroMart_Mobile/padrao.md
  - AgroMart Web:
    - Conheça o AgroMart Web: AgroMart_Web/AgroMartWeb.md
    - Arquitetura Web: AgroMart_Web/arquitetura.md
    - Guia de instalação: AgroMart_Web/guiaUsuario.md
    - Planejamento: AgroMart_Web/planejamento.md
    - Padrões de Desenvolvimento: AgroMart_Web/padrao.md
  - Guia de contribuição: Contribuicao.md
  - Processo de desenvolvimento: processo.md

extra:
  generator: false   # remove o "Made with Material for MkDocs"
