name: Template - Bug, Feature ou Documentação
description: Use este template para qualquer tipo de contribuição (bug, nova funcionalidade ou atualização de documentação)
title: "[ISSUE] - "
labels: []
body:
  - type: dropdown
    id: tipo
    attributes:
      label: Tipo de Issue
      description: Escolha o tipo principal desta issue
      options:
        - Bug
        - Nova Funcionalidade
        - Atualização de Documentação
    validations:
      required: true

  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: Descreva o problema, a funcionalidade ou a mudança necessária. Não esqueça de incluir o contexto e os objetivos da tarefa.
      placeholder: "O que precisa ser atualizado, corrigido ou desenvolvido?"
    validations:
      required: true

  - type: checkboxes
    id: modulos
    attributes:
      label: Repositórios afetados
      description: Selecione um ou mais repositórios relacionados a esta issue.
      options:
        - label: Web
        - label: API
        - label: Mobile
        - label: Docs
    validations:
      required: true

  - type: textarea
    id: detalhes
    attributes:
      label: Detalhes Técnicos (opcional)
      description: Informe detalhes adicionais, contexto ou dependências, afim de deixar a tarefa pronta para desenvolvimento (DoR).
      placeholder: "Ex: tecnologias envolvidas, endpoints, módulos afetados, dependências, etc."

